/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatapp;

import chatapp.Utils.Client.ThreadedInputStream;
import chatapp.Utils.Client.ThreadedOutputStream;
import chatapp.Utils.ClientInfo;
import java.io.IOException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kennywang
 */
public class PublicChatJF extends javax.swing.JFrame {
    private ClientInfo clientInfo;
    /**
     * Creates new form PublicChatJF
     */
    public PublicChatJF() {
        initComponents();
    }
    
    public PublicChatJF(ClientInfo clientInfo) throws IOException {
        this();
        
        //Setup
        this.clientInfo = clientInfo;
        initSetup();
        sendAndReceiveChatSetup();
    }
    
    private void initSetup() {
        String IPAddress = clientInfo.getSocket().getInetAddress().getHostAddress();
        String port = String.valueOf(clientInfo.getSocket().getPort());
        String username = clientInfo.getUsername();
        
        IPAddressLbl.setText(IPAddress);
        portLbl.setText(port);
        usernameLbl.setText(username);
    }
    
    private void sendAndReceiveChatSetup() throws IOException {
        // start input thread
        final ThreadedInputStream inputStream = new ThreadedInputStream(clientInfo.getSocket(), clientInfo.getDoneSignal(), chatTA);

        ExecutorService pool = Executors.newFixedThreadPool(1);
        pool.submit(inputStream);
        
        new ThreadedOutputStream(clientInfo.getSocket(), clientInfo.getDoneSignal(), clientInfo.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        chatTA = new javax.swing.JTextArea();
        messageTF = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        portLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        IPAddressLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chatTA.setEditable(false);
        chatTA.setColumns(1);
        chatTA.setRows(5);
        chatTA.setTabSize(1);
        jScrollPane1.setViewportView(chatTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 610, 290));
        getContentPane().add(messageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 540, 40));

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 60, 40));

        jLabel1.setText("Server Info:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Port          : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("IP Address: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel4.setText("User Info:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel5.setText("Username: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        portLbl.setText("Test");
        getContentPane().add(portLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        usernameLbl.setText("Test");
        getContentPane().add(usernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        IPAddressLbl.setText("Test");
        getContentPane().add(IPAddressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        String myChat = messageTF.getText();
        
        try {
            ThreadedOutputStream.sendMessage(myChat);
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }
        
        chatTA.append(clientInfo.getUsername() + ": " + myChat + "\n\r");
    }//GEN-LAST:event_sendBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublicChatJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublicChatJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublicChatJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublicChatJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublicChatJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IPAddressLbl;
    private javax.swing.JTextArea chatTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageTF;
    private javax.swing.JLabel portLbl;
    private javax.swing.JButton sendBtn;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
